[package]
name = "tsptools"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = { version = "0.8.5", features = ['small_rng'] }
rand_chacha = { version = "0.3.1", features = ['simd'] }
